include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - test/**
    - integration_test/**
    - lib/features/search/presentation/widgets/advanced_search_bar.dart
    - lib/core/services/search_analytics_service.dart
    - lib/core/services/search_export_service.dart
    - lib/core/services/search_performance_service.dart
    - lib/presentation/screens/language_settings_screen.dart