name: creapolis_app
description: "Creapolis - Sistema de gestión de proyectos con planificación automática"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  provider: ^6.1.2

  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # Local Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0

  # Routing
  go_router: ^14.6.2

  # UI Components
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  loading_animation_widget: ^1.2.1

  # Forms & Validation
  flutter_form_builder: ^10.0.0
  form_builder_validators: ^11.0.0

  # Date & Time
  intl: ^0.20.0
  timeago: ^3.7.0

  # Utils
  logger: ^2.4.0
  dartz: ^0.10.1
  url_launcher: ^6.3.1

  # Drag & Drop
  drag_and_drop_lists: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
