// Mocks generated by Mockito 5.4.4 from annotations
// in creapolis_app/test/presentation/bloc/workspace_invitation_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:creapolis_app/core/errors/failures.dart' as _i5;
import 'package:creapolis_app/domain/entities/workspace.dart' as _i9;
import 'package:creapolis_app/domain/entities/workspace_invitation.dart' as _i6;
import 'package:creapolis_app/domain/usecases/workspace/accept_invitation.dart'
    as _i8;
import 'package:creapolis_app/domain/usecases/workspace/create_invitation.dart'
    as _i7;
import 'package:creapolis_app/domain/usecases/workspace/get_pending_invitations.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetPendingInvitationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPendingInvitationsUseCase extends _i1.Mock
    implements _i3.GetPendingInvitationsUseCase {
  MockGetPendingInvitationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkspaceInvitation>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, List<_i6.WorkspaceInvitation>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.WorkspaceInvitation>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WorkspaceInvitation>>>);
}

/// A class which mocks [CreateInvitationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateInvitationUseCase extends _i1.Mock
    implements _i7.CreateInvitationUseCase {
  MockCreateInvitationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WorkspaceInvitation>> call(
          _i7.CreateInvitationParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.WorkspaceInvitation>>.value(
                _FakeEither_0<_i5.Failure, _i6.WorkspaceInvitation>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WorkspaceInvitation>>);
}

/// A class which mocks [AcceptInvitationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAcceptInvitationUseCase extends _i1.Mock
    implements _i8.AcceptInvitationUseCase {
  MockAcceptInvitationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.Workspace>> call(
          _i8.AcceptInvitationParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i9.Workspace>>.value(
            _FakeEither_0<_i5.Failure, _i9.Workspace>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i9.Workspace>>);
}
