// Mocks generated by Mockito 5.4.4 from annotations
// in creapolis_app/test/integration/workspace_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:creapolis_app/core/errors/failures.dart' as _i5;
import 'package:creapolis_app/domain/usecases/workspace/create_workspace.dart'
    as _i7;
import 'package:creapolis_app/domain/usecases/workspace/get_user_workspaces.dart'
    as _i3;
import 'package:creapolis_app/features/workspace/data/models/workspace_model.dart'
    as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetUserWorkspacesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserWorkspacesUseCase extends _i1.Mock
    implements _i3.GetUserWorkspacesUseCase {
  MockGetUserWorkspacesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Workspace>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Workspace>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Workspace>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Workspace>>>);
}

/// A class which mocks [CreateWorkspaceUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateWorkspaceUseCase extends _i1.Mock
    implements _i7.CreateWorkspaceUseCase {
  MockCreateWorkspaceUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>> call(
          _i7.CreateWorkspaceParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>.value(
            _FakeEither_0<_i5.Failure, _i6.Workspace>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>);
}
