// Mocks generated by Mockito 5.4.4 from annotations
// in creapolis_app/test/domain/usecases/workspace/get_user_workspaces_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:creapolis_app/core/errors/failures.dart' as _i5;
import 'package:creapolis_app/domain/entities/workspace_invitation.dart' as _i8;
import 'package:creapolis_app/domain/entities/workspace_member.dart' as _i7;
import 'package:creapolis_app/domain/repositories/workspace_repository.dart'
    as _i3;
import 'package:creapolis_app/features/workspace/data/models/workspace_model.dart'
    as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkspaceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceRepository extends _i1.Mock
    implements _i3.WorkspaceRepository {
  MockWorkspaceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Workspace>>>
      getUserWorkspaces() => (super.noSuchMethod(
            Invocation.method(
              #getUserWorkspaces,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Workspace>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Workspace>>(
              this,
              Invocation.method(
                #getUserWorkspaces,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Workspace>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>> getWorkspace(
          int? workspaceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkspace,
          [workspaceId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>.value(
            _FakeEither_0<_i5.Failure, _i6.Workspace>(
          this,
          Invocation.method(
            #getWorkspace,
            [workspaceId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>> createWorkspace({
    required String? name,
    String? description,
    String? avatarUrl,
    required _i6.WorkspaceType? type,
    _i6.WorkspaceSettings? settings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkspace,
          [],
          {
            #name: name,
            #description: description,
            #avatarUrl: avatarUrl,
            #type: type,
            #settings: settings,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>.value(
            _FakeEither_0<_i5.Failure, _i6.Workspace>(
          this,
          Invocation.method(
            #createWorkspace,
            [],
            {
              #name: name,
              #description: description,
              #avatarUrl: avatarUrl,
              #type: type,
              #settings: settings,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>> updateWorkspace({
    required int? workspaceId,
    String? name,
    String? description,
    String? avatarUrl,
    _i6.WorkspaceType? type,
    _i6.WorkspaceSettings? settings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkspace,
          [],
          {
            #workspaceId: workspaceId,
            #name: name,
            #description: description,
            #avatarUrl: avatarUrl,
            #type: type,
            #settings: settings,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>.value(
            _FakeEither_0<_i5.Failure, _i6.Workspace>(
          this,
          Invocation.method(
            #updateWorkspace,
            [],
            {
              #workspaceId: workspaceId,
              #name: name,
              #description: description,
              #avatarUrl: avatarUrl,
              #type: type,
              #settings: settings,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteWorkspace(int? workspaceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWorkspace,
          [workspaceId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteWorkspace,
            [workspaceId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.WorkspaceMember>>>
      getWorkspaceMembers(int? workspaceId) => (super.noSuchMethod(
            Invocation.method(
              #getWorkspaceMembers,
              [workspaceId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i7.WorkspaceMember>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.WorkspaceMember>>(
              this,
              Invocation.method(
                #getWorkspaceMembers,
                [workspaceId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.WorkspaceMember>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.WorkspaceMember>> updateMemberRole({
    required int? workspaceId,
    required int? userId,
    required _i6.WorkspaceRole? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberRole,
          [],
          {
            #workspaceId: workspaceId,
            #userId: userId,
            #role: role,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.WorkspaceMember>>.value(
                _FakeEither_0<_i5.Failure, _i7.WorkspaceMember>(
          this,
          Invocation.method(
            #updateMemberRole,
            [],
            {
              #workspaceId: workspaceId,
              #userId: userId,
              #role: role,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.WorkspaceMember>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeMember({
    required int? workspaceId,
    required int? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMember,
          [],
          {
            #workspaceId: workspaceId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeMember,
            [],
            {
              #workspaceId: workspaceId,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i8.WorkspaceInvitation>> createInvitation({
    required int? workspaceId,
    required String? email,
    required _i6.WorkspaceRole? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createInvitation,
          [],
          {
            #workspaceId: workspaceId,
            #email: email,
            #role: role,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.WorkspaceInvitation>>.value(
                _FakeEither_0<_i5.Failure, _i8.WorkspaceInvitation>(
          this,
          Invocation.method(
            #createInvitation,
            [],
            {
              #workspaceId: workspaceId,
              #email: email,
              #role: role,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.WorkspaceInvitation>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.WorkspaceInvitation>>>
      getPendingInvitations() => (super.noSuchMethod(
            Invocation.method(
              #getPendingInvitations,
              [],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i8.WorkspaceInvitation>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.WorkspaceInvitation>>(
              this,
              Invocation.method(
                #getPendingInvitations,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i8.WorkspaceInvitation>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>> acceptInvitation(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptInvitation,
          [token],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>.value(
            _FakeEither_0<_i5.Failure, _i6.Workspace>(
          this,
          Invocation.method(
            #acceptInvitation,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> declineInvitation(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #declineInvitation,
          [token],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #declineInvitation,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveActiveWorkspace(
          int? workspaceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveActiveWorkspace,
          [workspaceId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveActiveWorkspace,
            [workspaceId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int?>> getActiveWorkspaceId() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveWorkspaceId,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int?>>.value(
            _FakeEither_0<_i5.Failure, int?>(
          this,
          Invocation.method(
            #getActiveWorkspaceId,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int?>>);
}
