name: Android Build

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'creapolis_app/**'
      - '.github/workflows/android-build.yml'
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    paths:
      - 'creapolis_app/**'
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug/release)'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.9.2'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        working-directory: creapolis_app
        run: flutter pub get

      - name: Generate code
        working-directory: creapolis_app
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build APK (Debug)
        if: github.event_name == 'pull_request' || github.event.inputs.build_type == 'debug' || (github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/'))
        working-directory: creapolis_app
        run: flutter build apk --debug --verbose

      - name: Build APK (Release)
        if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.build_type == 'release'
        working-directory: creapolis_app
        env:
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        run: |
          if [ -n "$KEYSTORE_PASSWORD" ]; then
            echo "Building signed release APK"
            flutter build apk --release --verbose
          else
            echo "Building unsigned release APK (no keystore configured)"
            flutter build apk --release --verbose
          fi

      - name: Build App Bundle (Release)
        if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.build_type == 'release'
        working-directory: creapolis_app
        env:
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        run: |
          if [ -n "$KEYSTORE_PASSWORD" ]; then
            echo "Building signed App Bundle"
            flutter build appbundle --release --verbose
          else
            echo "Building unsigned App Bundle (no keystore configured)"
            flutter build appbundle --release --verbose
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-${{ github.sha }}
          path: |
            creapolis_app/build/app/outputs/flutter-apk/*.apk
          retention-days: 14

      - name: Upload App Bundle artifact
        if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.build_type == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: android-bundle-${{ github.sha }}
          path: |
            creapolis_app/build/app/outputs/bundle/release/*.aab
          retention-days: 30

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            creapolis_app/build/app/outputs/flutter-apk/app-release.apk
            creapolis_app/build/app/outputs/bundle/release/app-release.aab
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
